feat(code): add syntax highlighting for TypeScript
discord/SimpleAST pull request #37
Opened 2021-09-24 04:35 UTC by VoltrexMaster

Added syntax highlighting support for TypeScript.

2021-09-24 13:10 UTC, vBread reviewed
Quick skim for now, will do a more thorough review later. Type definitions also need to be handled.

2021-09-25 03:04 UTC, VoltrexMaster commented on simpleast-core/src/main/java/com/discord/simpleast/code/TypeScript.kt
> +          Pattern.compile("""^(var|let|const)(\s+[a-zA-Z_$][a-zA-Z0-9_$]*)""")
Const assertions are out of the scope of the field pattern and unreachable to it, no need to highlight it here.

2021-09-25 03:04 UTC, VoltrexMaster commented on simpleast-core/src/main/java/com/discord/simpleast/code/TypeScript.kt
> +        Pattern.compile("""^(@)(\s*[a-zA-Z_$][a-zA-Z0-9_$]*)""")
The parentheses are not highlighted and are not required.

2021-09-25 20:15 UTC, vBread requested changes
Test case for interfaces should be also be added.

2021-09-25 20:15 UTC, vBread commented on simpleast-core/src/test/java/com/discord/simpleast/code/TypeScriptRulesTest.kt
> +        "finally", "return", "throw")
```suggestion
        "throw", "finally", "return")
```
Test fails otherwise because of order.

2021-09-25 20:15 UTC, vBread commented on simpleast-core/src/main/java/com/discord/simpleast/code/TypeScript.kt
> +     "abstract|keyof|readonly|is|asserts|infer|override"
```suggestion
     "abstract|keyof|readonly|is|asserts|infer|override|intrinsic"
```
Forgot to mention `intrinsic` last review.

2021-09-25 20:15 UTC, vBread commented on simpleast-core/src/main/java/com/discord/simpleast/code/TypeScript.kt
> +          Pattern.compile("""^([\{\[\(\,;])(\s*(?:public|private|protected))?(\s*[a-zA-Z0-9_$]+)((?:\s*\?)?\s*:)""")
Index signatures and [mapping modifiers](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#mapping-modifiers) also need to be supported.

2021-11-04 19:36 UTC, merged